modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "eternal_starlight_vo"
version = "${version}"
displayName = "Eternal Starlight Vanilla Ores"
displayURL = "https://modrinth.com/mod/eternal-starlight-vo"
authors = "Minor2CCh"
description = '''
Add vanilla ores to Eternal Starlight Dimension.
'''
logoFile = "icon.png"

[[dependencies.eternal_starlight_vo]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.eternal_starlight_vo]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.eternal_starlight_vo]]
modId = "eternal_starlight"
type = "required"
versionRange = "(0.6.3,)"
ordering = "NONE"
side = "BOTH"


